version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'postgres'
    environment:
      - 'POSTGRES_DB=ticket'
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1'
#      - 'POSTGRES_HOST_AUTH_METHOD=trust'

  app:
    build: ./
    container_name: 'app'
    depends_on:
      - 'postgres'
    environment:
      - 'SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/ticket'
      - 'SPRING_DATASOURCE_USERNAME=postgres'
      - 'SPRING_DATASOURCE_PASSWORD=1'
      - 'SPRING_JPA_HIBERNATE_DDL_AUTO=update'
      - 'SPRING.JPA.PROPERTIES.HIBERNATE.SHOW_SQL=true'
    ports:
      - 8080:8080
#    links:
#      - 'postgres: localhost'
