version: '3'

services:
  postgres:
    image: 'postgres'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=1'
      - 'POSTGRES_DB=ticket'

  app:
    build: ./
    container_name: 'java_app'
    ports:
      - 8080:8080